# Generated by Django 5.1.3 on 2025-11-29 11:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc_id', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pond',
            fields=[
                ('pond_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('farm_name', models.CharField(default='Unknown Farm', max_length=255)),
                ('section', models.CharField(blank=True, max_length=100, null=True)),
                ('pond_name', models.CharField(max_length=255)),
                ('pond_type', models.CharField(blank=True, max_length=100, null=True)),
                ('pond_use', models.CharField(blank=True, max_length=100, null=True)),
                ('pond_depth', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('pond_depth_type', models.CharField(blank=True, max_length=50, null=True)),
                ('pond_size', models.DecimalField(decimal_places=2, default='0', max_digits=10)),
                ('area_type', models.CharField(blank=True, max_length=50, null=True)),
                ('species_type', models.CharField(blank=True, max_length=100, null=True)),
                ('species_value', models.CharField(blank=True, max_length=100, null=True)),
                ('stocking_time', models.TimeField(blank=True, null=True)),
                ('stocking_date', models.DateField(blank=True, null=True)),
                ('aerator', models.CharField(blank=True, max_length=100, null=True)),
                ('pond_shape', models.CharField(blank=True, max_length=100, null=True)),
                ('pond_status', models.CharField(default='active', max_length=50)),
                ('city_village', models.CharField(blank=True, max_length=100, null=True)),
                ('doc', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('connected', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, db_column='user_uid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ponds', to='users_app.user')),
                ('power_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ponds', to='apps.powercenter')),
            ],
        ),
        migrations.CreateModel(
            name='FeedingMotor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motor_id', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(max_length=20)),
                ('pond', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feeding_motor', to='apps.pond')),
            ],
        ),
        migrations.CreateModel(
            name='CheckTray',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tray_id', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(max_length=20)),
                ('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_trays', to='apps.pond')),
            ],
        ),
        migrations.CreateModel(
            name='WaterQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alkalinity', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ammonia', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('calcium', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('carbonate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('dissolved_oxygen', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('doc', models.IntegerField()),
                ('measurement_date', models.DateField()),
                ('hardness', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('bicarbonate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('iron', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('magnesium', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('nitrite', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ph', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('salinity', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('tds', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('turbidity', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('water_color', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('pond', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='water_quality', to='apps.pond')),
            ],
        ),
    ]
