# Generated by Django 5.2.8 on 2025-11-26 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pond_id', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PoweCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc_id', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FeedingMotor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motor_id', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('pond', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedingMotor', to='apps.pond')),
            ],
        ),
        migrations.CreateModel(
            name='CheckTray',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tray_id', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkTrays', to='apps.pond')),
            ],
        ),
        migrations.AddField(
            model_name='pond',
            name='power_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ponds', to='apps.powecenter'),
        ),
    ]
