# Generated by Django 5.1.3 on 2025-12-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pond',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pond',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
