# Generated by Django 5.2.8 on 2025-11-26 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PoweCenter',
            new_name='PowerCenter',
        ),
        migrations.AlterField(
            model_name='checktray',
            name='pond',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checktrays', to='apps.pond'),
        ),
    ]
