# Generated by Django 5.2.8 on 2025-11-26 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_rename_powecenter_powercenter_alter_checktray_pond'),
    ]

    operations = [
        migrations.AddField(
            model_name='pond',
            name='connected',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='checktray',
            name='pond',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_trays', to='apps.pond'),
        ),
        migrations.AlterField(
            model_name='checktray',
            name='tray_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='feedingmotor',
            name='motor_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='feedingmotor',
            name='pond',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feeding_motor', to='apps.pond'),
        ),
        migrations.AlterField(
            model_name='pond',
            name='pond_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='PondReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.CharField(max_length=20)),
                ('reading_values', models.JSONField(default=list)),
                ('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_readings', to='apps.pond')),
            ],
        ),
    ]
