# Generated by Django 5.1.3 on 2025-12-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_pond_created_at_alter_pond_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterquality',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
