# Generated by Django 5.2.8 on 2025-11-26 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_pond_connected_alter_checktray_pond_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pondreading',
            old_name='reading_values',
            new_name='DO',
        ),
        migrations.RemoveField(
            model_name='pondreading',
            name='sensor_type',
        ),
        migrations.AddField(
            model_name='pondreading',
            name='PH',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='pondreading',
            name='Salinity',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='pondreading',
            name='Temp',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='pondreading',
            name='pond',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='apps.pond'),
        ),
    ]
