# Generated by Django 5.2.8 on 2025-11-27 06:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_rename_reading_values_pondreading_do_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pond',
            name='aerator',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pond',
            name='area_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pond',
            name='city_village',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pond',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pond',
            name='doc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pond',
            name='farm_name',
            field=models.CharField(default='Unknown Farm', max_length=255),
        ),
        migrations.AddField(
            model_name='pond',
            name='pond_depth',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='pond',
            name='pond_depth_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pond',
            name='pond_name',
            field=models.CharField(default='Unknown Pond', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pond',
            name='pond_shape',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pond',
            name='pond_size',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pond',
            name='pond_status',
            field=models.CharField(default='active', max_length=50),
        ),
        migrations.AddField(
            model_name='pond',
            name='pond_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pond',
            name='pond_use',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pond',
            name='section',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pond',
            name='species_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pond',
            name='species_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pond',
            name='stocking_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pond',
            name='stocking_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pond',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pond',
            name='user_uid',
            field=models.CharField(default='unknown_user', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pond',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
    ]
