# Generated by Django 5.2.8 on 2025-11-27 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DO', models.JSONField(default=list)),
                ('PH', models.JSONField(default=list)),
                ('Salinity', models.JSONField(default=list)),
                ('Temp', models.JSONField(default=list)),
                ('pond', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='water_quality', to='apps.pond')),
            ],
        ),
        migrations.DeleteModel(
            name='PondReading',
        ),
    ]
