# Generated by Django 5.2.8 on 2025-11-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_waterquality_delete_pondreading'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='pond',
            name='pond_size',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=10),
        ),
    ]
